# train model
train: true
load: ~
model: 'fucr'
apex: True
device: 'cuda'
stop_std: 0.0007
stop_query_len: 100
max_num_iteration: 3000

# model structure parameters
scale: 0.5
dim: 3

# optimized parameters
learning_rate: 0.001
normalization: true
smooth_reg: 0.01
cyc_reg: 0.01
jdet_reg: 0.01
ncc_window_size: 5

# test parameters
fixed_disp_indexes: 5
group_index_list: [ 0, 1, 2, 3, 4, 5, 9, 8, 7, 6 ]

